;;;; reflection.lisp --- introspection over the package: docstring plumbing + API.md.
;;;;
;;;; Two jobs, both reading the live package rather than a hand-maintained list:
;;;;   * mirror CLOS slot :documentation onto the reader functions (so DESCRIBE and
;;;;     (documentation #'acc 'function) see the doc the CL idiom puts on the slot);
;;;;   * render the whole public API as Markdown (REVISION:API-MARKDOWN / `make api`).
;;;; Loads last, once every class + docstring exists.  (The keybinding reference is a
;;;; separate concern; see reference.lisp.)

(in-package #:revision)

;;; Slot accessors are documented on their slots (the CL idiom).  Mirror each slot's
;;; :documentation onto its reader's function documentation, so (documentation #'acc
;;; 'function) — and DESCRIBE / editor doc lookups — see it too.
(eval-when (:load-toplevel :execute)
  (let ((classes '()))
    (do-external-symbols (s (find-package :revision))
      (let ((c (find-class s nil))) (when c (push c classes))))
    (dolist (c classes)
      (ignore-errors (sb-mop:finalize-inheritance c))
      (dolist (slot (ignore-errors (sb-mop:class-direct-slots c)))
        (let ((doc (documentation slot t)))
          (when doc
            (dolist (r (sb-mop:slot-definition-readers slot))
              (when (and (fboundp r) (not (documentation r 'function)))
                (setf (documentation r 'function) doc)))))))))

;;; Type + conventional-name symbols (a DEFTYPE and a view name) — documented explicitly.
(eval-when (:load-toplevel :execute)
  (setf (documentation 'attr 'type)
          "A packed colour attribute: an (unsigned-byte 32) encoding foreground, background and style; build with MAKE-ATTR."
        (documentation 'edit 'variable)
          "Conventional NAME of the TEXT-EDIT subview inside an editor window (look it up with FIND-VIEW)."))

;;; --- a Markdown reference of the whole public API (regenerated by `make api`) --
(defun %api-kind (s)
  (cond ((macro-function s) :macro)
        ((find-class s nil) :class)
        ((and (fboundp s) (typep (fdefinition s) 'generic-function)) :generic)
        ((fboundp s) :function)
        ((and (boundp s) (constantp s)) :constant)
        ((boundp s) :variable)
        ((documentation s 'type) :type)
        (t :other)))
(defun %api-doc (s k)
  (case k
    ((:macro :generic :function) (documentation s 'function))
    ((:class :type) (or (and (find-class s nil) (documentation (find-class s) t)) (documentation s 'type)))
    ((:constant :variable) (documentation s 'variable))
    (t (or (documentation s 'variable) (documentation s 'type) (documentation s 'function)))))
(defun %api-sig (s)
  (ignore-errors (require :sb-introspect))
  (handler-case
      (let ((ll (uiop:symbol-call :sb-introspect :function-lambda-list s)))
        (if ll (format nil " ~(~a~)" ll) ""))
    (error () "")))

(defun api-markdown ()
  "Render the exported public API — every external symbol of :REVISION with its
docstring, grouped by kind — as a Markdown reference.  Regenerated by `make api`."
  (let ((buckets (make-hash-table)) (syms '()))
    (do-external-symbols (s (find-package :revision)) (push s syms))
    (dolist (s syms) (push s (gethash (%api-kind s) buckets)))
    (with-output-to-string (o)
      (format o "# revision — public API reference~2%The exported symbols of the ~
`revision` package, with their docstrings.  Generated from the live definitions by ~
`revision:api-markdown` (run `make api`); do not edit by hand.~2%")
      (dolist (spec '((:macro "Macros") (:class "Classes") (:generic "Generic functions")
                      (:function "Functions") (:variable "Variables") (:constant "Constants")
                      (:type "Types")))
        (destructuring-bind (k title) spec
          (let ((ss (sort (gethash k buckets) #'string< :key #'symbol-name)))
            (when ss
              (format o "## ~a~2%" title)
              (dolist (s ss)
                (let ((d (%api-doc s k)))
                  (format o "**`~(~a~)`~a**~@[  — ~a~]~2%"
                          (symbol-name s)
                          (if (member k '(:macro :generic :function)) (%api-sig s) "")
                          (and d (substitute #\Space #\Newline d))))))))))))
